---
network:
  version: 2
  ethernets:
    enp143s0f0:
      set-name: enp143s0f0
    enp143s0f1:
      set-name: enp143s0f1
    enp196s0f0:
      set-name: enp196s0f0
    enp196s0f1:
      set-name: enp196s0f1
  bonds:
    bond0:
      dhcp4: true  # Using DHCP for this example but not required
      interfaces:
        - enp143s0f0  # A side
        - enp196s0f0  # B side
      parameters:
        lacp-rate: fast
        mii-monitor-interval: 100
        mode: 802.3ad
    bond1:
      interfaces:
        - enp143s0f1  # A side
        - enp196s0f1  # B side
      parameters:
        lacp-rate: fast
        mii-monitor-interval: 100
        mode: 802.3ad
  vlans:
    vlan206:  # this is the interface that will be given to K8S via bond0
      accept-ra: false
      addresses:
        - 172.16.24.1/22  # Statically assigned IP address, increment on every node
      id: 206
      link: bond0
      mtu: 1500
    vlan306:  # this is the interface that will be given to Controllers via bond0
      accept-ra: false
      addresses:
        - 172.18.24.1/22  # Statically assigned IP address, increment on every node
      id: 306
      link: bond0
      mtu: 1500
    vlan406:  # this is the interface that will be given to Computes via bond0
      accept-ra: false
      addresses:
        - 172.20.24.1/22  # Statically assigned IP address, increment on every node
      id: 406
      link: bond0
      mtu: 1500
