bases:
  - ../base

patches:
  - target:
      kind: Ingress
      name: skyline
    patch: |-
      - op: add
        path: /spec/rules
        value:
          - host: skyline.dfw-ospcv2-staging.ohthree.com
            http:
              paths:
                - path: /
                  pathType: ImplementationSpecific
                  backend:
                    service:
                      name: skyline-apiserver
                      port:
                        name: "s-apiserver"
      - op: add
        path: /spec/tls
        value:
          - hosts:
            - skyline.dfw-ospcv2-staging.ohthree.com
            secretName: skyline-tls-public
      - op: add
        path: /metadata/annotations
        value:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          acme.cert-manager.io/http01-edit-in-place: "true"
