apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: neutron-gateway-route
  namespace: openstack
  labels:
    application: gateway-api
    service: HTTPRoute
    route: neutron
spec:
  parentRefs:
  - name: flex-gateway
    sectionName: cluster-tls
    namespace: nginx-gateway
  hostnames:
  - "neutron.cluster.local"
  rules:
    - backendRefs:
      - name: neutron-server
        port: 9696
