resources:
  - ns-ingress-nginx.yaml

helmCharts:
  - name: ingress-nginx
    releaseName: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    valuesInline:
      deployment:
        cluster:
          class: nginx-cluster
    valuesFile: helm/ingress-helm-overrides.yaml
    namespace: ingress-nginx
    includeCRDs: true
