apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: grafana
  namespace: openstack
spec:
  # If you want the database to be created with a different name than the resource name
  # name: data-custom
  mariaDbRef:
    name: mariadb-galera
  characterSet: utf8
  collate: utf8_general_ci
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: grafana
  namespace: openstack
spec:
  # If you want the user to be created with a different name than the resource name
  # name: user-custom
  mariaDbRef:
    name: mariadb-galera
  passwordSecretKeyRef:
    name: grafana-db
    key: password
  # This field is immutable and defaults to 10
  maxUserConnections: 20
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant
  namespace: openstack
spec:
  mariaDbRef:
    name: mariadb-galera
  privileges:
    - "ALL"
  database: "grafana"
  table: "*"
  username: grafana
  grantOption: true
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s
