helmCharts:
  - name: memcached
    repo: https://marketplace.azurecr.io/helm/v1/repo
    releaseName: memcached
    valuesInline:
      architecture: standalone
      autoscaling:
        enabled: false
      resources:
        requests:
          memory: 1Gi
      persistence:
        enabled: true
        size: 1Gi
    includeCRDs: true
    namespace: openstack
