---
# tasks file for monitor_setup

- hosts: all
  become: true
  gather_facts: true
  environment: "{{ deployment_environment_variables | default({}) }}"
  tasks:
    - name: Create monitor directory structure on nova compute nodes
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        recurse: yes
        mode: '0755'
        owner: root
        group: root
      loop: "{{ monitor_dirs }}"


- hosts: openstack_compute_nodes
  ansible.builtin.include_tasks:
    file: monitor_compute.yml
    apply:
      tags:
        - compute
  tags:
    - always


- hosts: cinder_storage_nodes
  ansible.builtin.include_tasks:
    file: monitor_storage.yml
    apply:
      tags:
        - cinder_storage_nodes
  tags:
    - always


