apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
spec:
  template:
    spec:
      containers:
        - name: memcached
          volumeMounts:
            - name: persistence
              mountPath: /data
      volumes:
        - name: persistence
          persistentVolumeClaim:
            claimName: memcached-pvc
