resources:
  - './namespace.yaml'
  - './gatewayclass.yaml'
  - './gateway.yaml'
namespace: envoy-gateway-system
helmGlobals:
  chartHome: ../../../submodules/envoyproxy-gateway/charts/
helmCharts:
- name: gateway-helm
  valuesFile: values.yaml
  includeCRDs: true
  releaseName: envoyproxy-gateway
  valuesInline:
    kubernetesClusterDomain: cluster.local
