#### EDIT THESE TWO VARIABLES WITH YOUR VALUES
custom_host: grafana.example.com # TODO: update this value to the FQDN of your grafana site
tenant_id: 122333 # TODO: update this value to use your Azure Tenant ID
####

ingress:
  enabled: false

image:
  tag: "10.3.3"

extraSecretMounts:
  - name: azure-client-secret-mount
    secretName: azure-client
    defaultMode: 0440
    mountPath: /etc/secrets/azure-client
    readOnly: true
  - name: grafana-db-secret-mount
    secretName: grafana-db
    defaultMode: 0440
    mountPath: /etc/secrets/grafana-db
    readOnly: true
nodeSelector:
  openstack-control-plane: enabled
grafana.ini:
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  server:
    domain: "{{ .Values.custom_host }}"  # Ref: custom_host variable above
    root_url: "https://{{ .Values.custom_host }}"  # Ref: custom_host variable above
  auth.azuread:
    name: Azure AD
    enabled: true
    allow_sign_up: true
    auto_login: false
    client_id: $__file{/etc/secrets/azure-client/client_id}
    client_secret: $__file{/etc/secrets/azure-client/client_secret}
    scopes: openid email profile
    auth_url: "https://login.microsoftonline.com/{{ .Values.tenant_id }}/oauth2/v2.0/authorize"
    token_url: "https://login.microsoftonline.com/{{ .Values.tenant_id }}/oauth2/v2.0/token"
    allowed_organizations: "{{ .Values.tenant_id }}"
    role_attribute_strict: false
    allow_assign_grafana_admin: false
    skip_org_role_sync: false
    use_pkce: true
  database:
    type: mysql
    host: mariadb-cluster-primary.openstack.svc:3306
    user: $__file{/etc/secrets/grafana-db/username}
    password:  $__file{/etc/secrets/grafana-db/password}
    name: grafana
