apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: fifo
resources:
  - ../base

patches:
  - target:
      kind: StatefulSet
      name: memcached
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: METRICS_ENABLED
          value: "true"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SERVICEMONITOR_ENABLED
          value: "true"
