apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
spec:
  template:
    spec:
      containers:
        - name: memcached
          resources:
            requests:
              memory: "1Gi"
          env:
            - name: METRICS_ENABLED
              value: "true"
            - name: SERVICEMONITOR_ENABLED
              value: "true"
          volumeMounts:
            - name: persistence
              mountPath: /data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: In
                    values:
                      - worker

