apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: glance-gateway-route
  namespace: openstack
  labels:
    application: gateway-api
    service: HTTPRoute
    route: glance
spec:
  parentRefs:
  - name: flex-gateway
    sectionName: cluster-tls
    namespace: nginx-gateway
  hostnames:
  - "glance.cluster.local"
  rules:
    - backendRefs:
      - name: glance-api
        port: 9292
