---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: placement-api
  namespace: openstack
  labels:
    application: gateway-api
    service: HTTPRoute
    route: placement
spec:
  parentRefs:
  - name: flex-gateway
    sectionName: cluster-tls
    namespace: nginx-gateway
  hostnames:
  - "placement.cluster.local"
  rules:
    - backendRefs:
      - name: placement-api
        port: 8778
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: metadata-gateway-route
  namespace: openstack
  labels:
    application: gateway-api
    service: HTTPRoute
    route: nova-metadata
spec:
  parentRefs:
  - name: flex-gateway
    sectionName: cluster-tls
    namespace: nginx-gateway
  hostnames:
  - "metadata.cluster.local"
  rules:
    - backendRefs:
      - name: nova-metadata
        port: 8775
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nova-gateway-route
  namespace: openstack
  labels:
    application: gateway-api
    service: HTTPRoute
    route: nova
spec:
  parentRefs:
  - name: flex-gateway
    sectionName: cluster-tls
    namespace: nginx-gateway
  hostnames:
  - "nova.cluster.local"
  rules:
    - backendRefs:
      - name: nova-api
        port: 8774
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: novnc-gateway-route
  namespace: openstack
  labels:
    application: gateway-api
    service: HTTPRoute
    route: novnc
spec:
  parentRefs:
  - name: flex-gateway
    sectionName: cluster-tls
    namespace: nginx-gateway
  hostnames:
  - "novnc.cluster.local"
  rules:
    - backendRefs:
      - name: nova-novncproxy
        port: 6080
