bases:
  - "../base"

patches:
  - target:
      kind: MariaDB
      name: mariadb-galera
    patch: |-
      - op: replace
        path: /spec/affinity/enableAntiAffinity
        value: false
      - op: replace
        path: /spec/replicas
        value: 2
