---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: barbican-route
  namespace: openstack
spec:
  parentRefs:
  - name: flex-gateway
    sectionName: cluster-tls
    namespace: nginx-gateway
  hostnames:
  - "barbican.cluster.local"
  rules:
    - backendRefs:
      - name: barbican-api
        port: 9311
