apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alertmanger-gateway-route
  namespace: prometheus
spec:
  parentRefs:
  - name: flex-gateway
    sectionName: http
    namespace: nginx-gateway
  hostnames:
  - "alertmanager.sjc.ohthree.com"
  rules:
    - backendRefs:
      - name: kube-prometheus-stack-alertmanager
        port: 9093
