- name: Partition disks, etc.

  hosts:
    - "!block*"
    - "!ceph*"
    - "!overseer*"

  become: yes
  gather_facts: no

  tasks:

    - name: Gather disk facts
      ansible.builtin.setup:
        gather_subset:
          - hardware

    - name: List unpartitioned NVMe devices
      set_fact:
        nvm_unpartitioned: "{{ nvme_unpartitioned | default([]) + [item.key] }}"
      loop: "{{ ansible_devices | dict2items }}"
      when:
        - ansible_devices[item.key].partitions | length < 1
        - "'nvme' in item.key"

    - name: Partition unpartitioned NVMe devices
      community.general.parted:
        device: "/dev/{{ item }}"
        number: 1
        label: gpt
        flags: [ lvm ]
        state: present
        part_end: 100%
      loop: "{{ nvm_unpartitioned | default([])}}"

    # community.general.lvg requires immediately putting the PV
    # in a volume group, so I used the `command` module.
    - name: Create PV for partitioned NVMe disks
      command: "pvcreate /dev/{{ item }}p1"
      loop: "{{ nvm_unpartitioned | default([]) }}"
