resources:
  - all.yaml
  - hpa-glance-api.yaml

patches:
  - target:
      kind: PersistentVolumeClaim
      name: glance-images
    patch: |-
      - op: replace
        path: /spec/accessModes
        value: ["ReadWriteMany"]
