---
# Copyright 2024-Present, Rackspace Technology, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: "Map node to label/role"
  ansible.builtin.set_fact:
    kubectl_options: |
      {% set _kctl = kubectl_options |default([]) %}
      {% if (item.hosts |length) > 0 %}
      {%   for node in item.hosts %}
      {%     set _label = "" %}
      {%     set _role = "" %}
      {%     set _node = "label node " + node + " " %}
      {%     if item.label is defined %}
      {%       set _label = item.label %}
      {%     endif %}
      {%     if item.role is defined %}
      {%       set _role = " role=" + item.role %}
      {%     endif %}
      {%     if _kctl.append(_node + _label + _role) %}{% endif %}
      {%   endfor %}
      {% endif %}
      {{ _kctl }}
  loop:
    - hosts: "{{ groups['openstack_control_plane'] }}"
      label: "openstack-control-plane=enabled"
    - hosts: "{{ groups['openstack_compute_nodes'] }}"
      label: "openstack-compute-node=enabled"
    - hosts: "{{ groups['openstack_network_nodes'] |default([]) }}"
      label: "openstack-network-node=enabled"
    - hosts: "{{ groups['ovn_network_nodes'] |default([]) }}"
      label: "openstack-network-node=enabled"
    - hosts: "{{ groups['openstack_storage_nodes'] |default([]) }}"
      label: "openstack-storage-plane=enabled"
    - hosts: "{{ groups['cinder_storage_nodes'] |default([]) }}"
      label: "openstack-storage-node=enabled"
    - hosts: "{{ groups['storage_nodes'] |default([]) }}"
      role: "storage-node"
    - hosts: "{{ groups['ceph_storage_nodes'] |default([]) }}"
      label: "ceph-storage-node=enabled"
      role: "storage-node"

- name: "Apply label"
  ansible.builtin.shell: |
    kubectl --kubeconfig="{{ kubeconfig_file }}" {{ item }}
  args:
    executable: /bin/bash
  loop: "{{ kubectl_options }}"
