apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: flex-gateway
  namespace: nginx-gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-gw
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  gatewayClassName: nginx
  listeners:
  - name: o3-http
    port: 80
    protocol: HTTP
    hostname: "*.sjc.ohthree.com"
    allowedRoutes:
      namespaces:
        from: All
  - name: rackspacecloud-http
    port: 80
    protocol: HTTP
    hostname: "*.sjc3.rackspacecloud.com"
    allowedRoutes:
      namespaces:
        from: All
  - name: am-https
    hostname: "alertmanager.sjc.ohthree.com"
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: alertmanager-gw-tls-secret
  - name: prom-https
    hostname: "prometheus.sjc.ohthree.com"
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: prometheus-gw-tls-secret
  - name: graf-https
    hostname: "grafana.sjc3.rackspacecloud.com"
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: grafana-gw-tls-secret
