helmCharts:
  - name: ingress-nginx
    releaseName: ingress-grafana-internal
    repo: https://kubernetes.github.io/ingress-nginx
    valuesInline:
      deployment:
        cluster:
          class: nginx
    valuesFile: helm/ingress-helm-overrides.yaml
    namespace: grafana
    includeCRDs: true
