additionalPrometheusRulesMap:
  rabbitmq-alerts:
    groups:
    - name: Prometheus Alerts
      rules:
      - alert: RabbitQueueSizeTooLarge
        expr: rabbitmq_queuesTotal>25
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Rabbit queue size too large (instance {{ `{{ $labels.instance }}` }} )"
