additionalPrometheusRulesMap:
  rabbitmq-alerts:
    groups:
    - name: Prometheus Alerts
      rules:
      - alert: RabbitQueueSizeTooLarge
        expr: rabbitmq_queuesTotal>25
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Rabbit queue size too large (instance {{ `{{ $labels.instance }}` }} )"
  database-alerts:
    groups:
    - name: Mysql Alerts
      rules:
      - alert: MysqlDown
        expr: mysql_up == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: MariaDB down (instance {{ $labels.instance }})
          description: "MariaDB instance is down on {{ $labels.instance }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: MysqlTooManyConnections(>80%)
        expr: max_over_time(mysql_global_status_threads_connected[1m]) / mysql_global_variables_max_connections * 100 > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Database too many connections (> 90%) (instance {{ $labels.instance }})
          description: "More than 90% of MySQL connections are in use on {{ $labels.instance }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: MysqlSlowQueries
        expr: increase(mysql_global_status_slow_queries[1m]) > 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: MySQL slow queries (instance {{ $labels.instance }})
          description: "MySQL server mysql has some new slow query.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: MysqlRestarted
        expr: mysql_global_status_uptime < 60
        for: 0m
        labels:
          severity: info
        annotations:
          summary: MySQL restarted (instance {{ $labels.instance }})
          description: "MySQL has just been restarted, less than one minute ago on {{ $labels.instance }}.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
