resources:
  - ns-prometheus.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: kube-prometheus-stack
    namespace: prometheus
    includeCRDs: true
    valuesFile: values.yaml
    additionalValuesFiles:
      - alerting_rules.yaml
