resources:
  - ns-mariadb.yaml

helmCharts:
  - name: mariadb-operator
    repo: https://mariadb-operator.github.io/mariadb-operator
    releaseName: mariadb-operator
    valuesInline:
      clusterName: cluster.local
      webhook:
        cert:
          certManager:
            enabled: true
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node-role.kubernetes.io/worker
                      operator: In
                      values:
                        - worker
      metrics:
        enabled: true
      extrArgs:
        - '--log-maxscale'
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: In
                    values:
                      - worker
    includeCRDs: true
    version: 0.27.0
    namespace: mariadb-system
