resources:
  - ns-mariadb.yaml

helmCharts:
  - name: mariadb-operator
    repo: https://mariadb-operator.github.io/mariadb-operator
    releaseName: mariadb-operator
    valuesInline:
      clusterName: cluster.local
      webhook:
        cert:
          certManager:
            enabled: true
      metrics:
        enabled: true
    includeCRDs: true
    version: 0.27.0
    namespace: mariadb-system
