---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: skyline-api
  namespace: openstack
  labels:
    application: gateway-api
    service: HTTPRoute
    route: skyline
spec:
  parentRefs:
  - name: flex-gateway
    sectionName: cluster-tls
    namespace: nginx-gateway
  hostnames:
  - "skyline.cluster.local"
  rules:
    - backendRefs:
      - name: skyline-apiserver
        port: 9999
