---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: octavia-api
  namespace: openstack
  labels:
    application: gateway-api
    service: HTTPRoute
    route: octavia
spec:
  parentRefs:
  - name: flex-gateway
    sectionName: cluster-tls
    namespace: nginx-gateway
  hostnames:
  - "octavia.cluster.local"
  rules:
    - backendRefs:
      - name: octavia-api
        port: 9876
