apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
  namespace: openstack
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
  username: mariadb
  database: mariadb

  storage:
    size: 10Gi
    storageClassName: general
    resizeInUseVolumes: true
    waitForVolumeResize: true
    volumeClaimTemplate:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: general

  replicas: 3
  podSecurityContext:
    runAsUser: 0

  # point to an existing MaxScale instance. Doing this will delegate tasks such as primary failover to MaxScale.
  maxScaleRef:
    name: maxscale-galera

  galera:
    enabled: true
    primary:
      podIndex: 0
      automaticFailover: true
    sst: mariabackup
    availableWhenDonor: false
    galeraLibPath: /usr/lib/galera/libgalera_smm.so
    replicaThreads: 1
    agent:
      image: ghcr.io/mariadb-operator/mariadb-operator:v0.0.27
      port: 5555
      kubernetesAuth:
        enabled: true
      gracefulShutdownTimeout: 1s
    recovery:
      enabled: true
      minClusterSize: 50%
      clusterHealthyTimeout: 30s
      clusterBootstrapTimeout: 10m
      podRecoveryTimeout: 3m
      podSyncTimeout: 3m
    initContainer:
      image: ghcr.io/mariadb-operator/mariadb-operator:v0.0.27
    config:
      reuseStorageVolume: false
      volumeClaimTemplate:
        resources:
          requests:
            storage: 10Gi
        accessModes:
          - ReadWriteOnce

  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: primary
  connection:
    secretName: mariadb-galera-conn
    secretTemplate:
      key: dsn

  primaryService:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: primary
  primaryConnection:
    secretName: mariadb-galera-conn-primary
    secretTemplate:
      key: dsn

  secondaryService:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: primary
  secondaryConnection:
    secretName: mariadb-galera-conn-secondary
    secretTemplate:
      key: dsn

  affinity:
    enableAntiAffinity: true

  tolerations:
    - key: "k8s.mariadb.com/ha"
      operator: "Exists"
      effect: "NoSchedule"

  podDisruptionBudget:
    maxUnavailable: 33%

  updateStrategy:
    type: RollingUpdate

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=ROW
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M
    max_connections=10240
    open_files_limit=10240
    max-connect-errors=1000000

  resources:
    requests:
      memory: 256Mi

  metrics:
    enabled: true
