# This ConfigMap contains variables controlling the run of the OVN DB backups.
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-backup-config
  namespace: kube-system
data:
  RETENTION_DAYS: "30"
  BACKUP_DIR: "/backup"
  # You probably want to place this on the PersistentVolume so that it doesn't
  # get deleted with the pod by cron, or use /dev/null if you don't care.
  # You can use `kubectl logs` since log messages also go to STDOUT.
  LOG_FILE: "/backup/upload.log"

  # From here forward, variables for uploading to Rackspace OSPCv1 Cloud Files
  UPLOAD_OSPC_V1: "false"
  # Nothing after this line makes any difference unless you used
  # UPLOAD_OSPC_V1: "true"
  # above.
  CF_REGION: "dfw" # OSPCv1 Cloud Files region to use
  # You should probably include the name of the environment in CONTAINER
  CONTAINER: "test-ovn-backup"
  # Standard log levels DEBUG, INFO, WARNING, ERROR, CRITICAL
  # DEBUG also does `set -x` toward the beginning of the backup script.
  LOG_LEVEL: INFO
