name: Helm GitHub Actions for loki

on:
  pull_request:
    paths:
      - helm-configs/loki/**
      - .github/workflows/helm-loki.yaml
jobs:
  helm:
    name: Helm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
        with:
          version: latest
          token: "${{ secrets.GITHUB_TOKEN }}"
        id: helm
      - name: Kubectl Install
        working-directory: /usr/local/bin/
        run: |
            if [ ! -f /usr/local/bin/kubectl ]; then
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              chmod +x ./kubectl
            fi
      - name: Run Helm Template
        run: |
          ${{ steps.helm.outputs.helm-path }} repo add grafana https://grafana.github.io/helm-charts
          ${{ steps.helm.outputs.helm-path }} repo update
          ${{ steps.helm.outputs.helm-path }} template --values ${{ github.workspace }}/helm-configs/loki/loki-helm-minio-overrides-example.yaml \
                                                       --namespace grafana \
                                                        loki grafana/loki > /tmp/rendered.yaml
      - name: Return helm Build
        uses: actions/upload-artifact@v2
        with:
          name: helm-loki-artifact
          path: /tmp/rendered.yaml
