name: Helm GitHub Actions for keystone

on:
  pull_request:
    paths:
      - helm-configs/keystone/**
      - kustomize/keystone/**
      - .github/workflows/helm-keystone.yaml
jobs:
  helm:
    strategy:
      matrix:
        overlays:
          - base
          - aio
    name: Helm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
        with:
          version: latest
          token: "${{ secrets.GITHUB_TOKEN }}"
        id: helm
      - name: Kubectl Install
        working-directory: /usr/local/bin/
        run: |
            if [ ! -f /usr/local/bin/kubectl ]; then
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              chmod +x ./kubectl
            fi
      - name: Pull OSH submodules
        run: |
            git submodule update --init submodules/openstack-helm
            git submodule update --init submodules/openstack-helm-infra
      - name: Make OSH submodule
        run: |
            cd submodules/openstack-helm
            make keystone
      - name: Run Helm Template
        run: |
          cd submodules/openstack-helm
          ${{ steps.helm.outputs.helm-path }} template keystone ./keystone \
            --namespace=openstack \
            --wait \
            --timeout 120m \
            -f ${{ github.workspace }}/helm-configs/keystone/keystone-helm-overrides.yaml \
            --post-renderer ${{ github.workspace }}/kustomize/kustomize.sh \
            --post-renderer-args keystone/${{ matrix.overlays }} > /tmp/rendered.yaml
      - name: Return helm Build
        uses: actions/upload-artifact@v2
        with:
          name: helm-keystone-artifact-${{ matrix.overlays }}
          path: /tmp/rendered.yaml
