name: Kustomize GitHub Actions for rabbitmq-cluster

on:
  pull_request:
    paths:
      - base-kustomize/rabbitmq-cluster/**
      - .github/workflows/kustomize-rabbitmq-cluster.yaml
jobs:
  kustomize:
    strategy:
      matrix:
        overlays:
          - base
          - aio
    name: Kustomize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Kustomize Install
        working-directory: /usr/local/bin/
        run: |
          if [ ! -f /usr/local/bin/kustomize ]; then
            curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | sudo bash
          fi
      - name: Run Kustomize Build
        run: |
          kustomize build base-kustomize/rabbitmq-cluster/${{ matrix.overlays }} > /tmp/rendered.yaml
      - name: Return Kustomize Build
        uses: actions/upload-artifact@v4
        with:
          name: kustomize-rabbitmq-cluster-artifact-${{ matrix.overlays }}
          path: /tmp/rendered.yaml
