name: Kustomize GitHub Actions for libvirt

on:
  pull_request:
    paths:
      - base-kustomize/libvirt/**
      - .github/workflows/kustomize-libvirt.yaml
jobs:
  kustomize:
    name: Kustomize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
        with:
          version: latest
          token: "${{ secrets.GITHUB_TOKEN }}"
        id: helm
      - name: Kustomize Install
        working-directory: /usr/local/bin/
        run: |
          if [ ! -f /usr/local/bin/kustomize ]; then
            curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | sudo bash
          fi
      - name: Pull OSH infra submodule
        run: |
          git submodule update --init submodules/openstack-helm-infra
      - name: Make OSH infra submodule
        run: |
          cd submodules/openstack-helm-infra
          make libvirt
      - name: Run Kustomize Build
        run: |
          kustomize build base-kustomize/libvirt --enable-helm --helm-command ${{ steps.helm.outputs.helm-path }} > /tmp/rendered.yaml
      - name: Return Kustomize Build
        uses: actions/upload-artifact@v4
        with:
          name: kustomize-libvirt-artifact
          path: /tmp/rendered.yaml
