name: Kustomize GitHub Actions for topolvm

on:
  pull_request:
    paths:
      - base-kustomize/topolvm/**
      - .github/workflows/kustomize-topolvm.yaml
jobs:
  kustomize:
    strategy:
      matrix:
        overlays:
          - general
    name: Kustomize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
        with:
          version: latest
          token: "${{ secrets.GITHUB_TOKEN }}"
        id: helm
      - name: Kustomize Install
        working-directory: /usr/local/bin/
        run: |
          if [ ! -f /usr/local/bin/kustomize ]; then
            curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | sudo bash
          fi
      - name: Run Kustomize Build
        run: |
          kustomize build base-kustomize/topolvm/${{ matrix.overlays }} --enable-helm --helm-command ${{ steps.helm.outputs.helm-path }} > /tmp/rendered.yaml
      - name: Return Kustomize Build
        uses: actions/upload-artifact@v4
        with:
          name: kustomize-topolvm-artifact-${{ matrix.overlays }}
          path: /tmp/rendered.yaml
