name: Kustomize GitHub Actions for glance-resources

on:
  pull_request:
    paths:
      - kustomize/glance-resources/**
      - .github/workflows/kustomize-glance-resources.yaml
jobs:
  kustomize:
    strategy:
      matrix:
        overlays:
          - base
    name: Kustomize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Kustomize Install
        working-directory: /usr/local/bin/
        run: |
          if [ ! -f /usr/local/bin/kustomize ]; then
            curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | sudo bash
          fi
      - name: Run Kustomize Build
        run: |
          kustomize build kustomize/glance-resources/${{ matrix.overlays }} > /tmp/rendered.yaml
      - name: Return Kustomize Build
        uses: actions/upload-artifact@v2
        with:
          name: kustomize-glance-resources-artifact-${{ matrix.overlays }}
          path: /tmp/rendered.yaml
