name: Kustomize GitHub Actions for Backups directory

on:
  pull_request:
    paths:
      - kustomize/backups/etcd/**
      - .github/workflows/kustomize-etcd-backups.yaml
jobs:
  kustomize:
    name: Kustomize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: azure/setup-helm@v3
        with:
          version: latest
          token: "${{ secrets.GITHUB_TOKEN }}"
        id: helm
      - name: Kustomize Install
        working-directory: /usr/local/bin/
        run: |
          if [ ! -f /usr/local/bin/kustomize ]; then
            curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | sudo bash
          fi
      - name: Run Kustomize Build
        run: |
          kustomize build kustomize/backups/etcd/  > /tmp/rendered.yaml
      - name: Return Kustomize Build
        uses: actions/upload-artifact@v2
        with:
          name: kustomize-etcd-backup-artifact
          path: /tmp/rendered.yaml
